version: "3.5"
services:
  #PHP Service
  yaraku_php72:
    build:
      context: docker/images/php72
      dockerfile: Dockerfile
    container_name: yaraku_php72
    tty: true
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
    - ./:/var/www
    - ./docker/images/php72/config/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - yaraku-network

  #Nginx Service
  yaraku_nginx:
    image: nginx:alpine
    container_name: yaraku_nginx
    restart: unless-stopped
    tty: true
    ports:
    - "8090:80"
    #      - "443:443"
    volumes:
    - ./:/var/www
    - ./docker/images/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
    - yaraku-network

  #Mysql Service
  #todo mount container storage
  yaraku_mysql:
    image: mysql:5.7
    container_name: yaraku_mysql
    networks:
    - yaraku-network
    environment:
    - MYSQL_DATABASE=yaraku
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password
    ports:
    - "3306:3306"

networks:
  yaraku-network:
    driver: bridge